name: Build and Deploy to itch.io

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    # Job name, can be anything
    name: Build and Deploy to itch.io
    steps:
      # Always include the checkout step so that 
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v3.3.0
  
    - name: export game
      id: export
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v5.2.0
      with:
        # Defining all the required inputs
        use_godot_3: true
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.6/rc1/Godot_v3.6-rc1_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.6/rc1/Godot_v3.6-rc1_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        cache: true

    - name: Install butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler        
        sudo mv butler /usr/local/bin/
        butler -V

    - name: Upload to itch.io
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        ITCH_IO_USER: ${{ vars.ITCH_IO_USER }}
        GAME_NAME: ${{ vars.GAME_NAME }}
        EXPORT_DIR: ${{ steps.export.outputs.build_directory }}
      run: |
         echo ${{ steps.export.outputs.build_directory }}
         butler push $EXPORT_DIR $ITCH_IO_USER/$GAME_NAME:web